version: "3.8"

services:
  api:
    container_name: geoip_api
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./data:/usr/share/GeoIP
    restart: always

networks:
  default:
    driver: bridge
