name: Daily Docker Image Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - "package.json"
      - "bun.lockb"
      - "tsconfig.json"
      - "entrypoint.sh"
      - "geoip.conf"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
  CONTAINER_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with daily updated databases
        run: |
          # Get current date in DDMMYY format
          DATE_TAG=$(date +'%y%m%d')
          docker build --platform linux/amd64 \
            --build-arg GEOIPUPDATE_ACCOUNT_ID=${{ secrets.GEOIPUPDATE_ACCOUNT_ID }} \
            --build-arg GEOIPUPDATE_LICENSE_KEY=${{ secrets.GEOIPUPDATE_LICENSE_KEY }} \
            --tag ${{ env.IMAGE_NAME }}:latest --tag ${{ env.IMAGE_NAME }}:${GITHUB_SHA::7} --tag ${{ env.IMAGE_NAME }}:${DATE_TAG} --file ./Dockerfile .
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:${DATE_TAG}